### ISSUE TITLE
Syntax error on execution

### ISSUE THREAD

**Issue by jferch** [macearl/Wallhaven-Downloader#11]
Hey there,

first of all thanks for sharing this script. I'm experiencing the following error while trying to pull my favorites section and can't figure it out:

```
./wallhaven.sh: line 265: ((: count< 48 && count<  : syntax error: operand expected (error token is "<  ")
```
I copied the line from the script:
```
for (( count=0, page="$STARTPAGE"; count< "$WPNUMBER" && count< "$favnumber" ; count=count+64, page=page+1 ));
```
Any ideas why this is happening? I'm running Arch with the latest packages installed. Let me know if you  need more information. Thanks!

**Comment by macearl** [comment]
Should be fixed now, its a bit ugly but given that the whole favorites thing needs to be replaced to be able to download more than the default collection it should suffice

**Comment by jferch** [comment]
Yes, the issue is resolved, thank you very much!
