### ISSUE TITLE
Wallpapers start to download but fail

### ISSUE THREAD

**Issue by Alteration** [macearl/Wallhaven-Downloader#13]
This is all that wget outputs, the wallpaper numbers are appended to downloaded.txt but the files aren't there

> Download Page 1--2016-08-28 22:29:23--  https://alpha.wallhaven.cc/search?page=1&categories=111&purity=110&resolutions=&ratios=&sorting=random&order=desc
> Resolving alpha.wallhaven.cc (alpha.wallhaven.cc)... 104.28.20.70, 104.28.21.70, 2400:cb00:2048:1::681c:1446, ...
> Connecting to alpha.wallhaven.cc (alpha.wallhaven.cc)|104.28.20.70|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: unspecified [text/html]
> Saving to: 'tmp’
> 
>     [ <=>                                                  ] 41,226      --.-K/s   in 0.1s
> 
> 2016-08-28 22:29:25 (270 KB/s) - 'tmp’ saved [41226]
> 
> 
>     - done!
> Download Wallpapers from Page 1--2016-08-28 22:29:25--  https://alpha.wallhaven.cc/wallpaper/22080
> Resolving alpha.wallhaven.cc (alpha.wallhaven.cc)... 104.28.21.70, 104.28.20.70, 2400:cb00:2048:1::681c:1546, ...
> Connecting to alpha.wallhaven.cc (alpha.wallhaven.cc)|104.28.21.70|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: unspecified [text/html]
> Saving to: '22080’
> 
>     [ <=>                                                  ] 24,803      --.-K/s   in 0.1s
> 
> 2016-08-28 22:29:28 (220 KB/s) - '22080’ saved [24803]
> 
> --2016-08-28 22:29:28--  https://alpha.wallhaven.cc/wallpaper/233768
> Resolving alpha.wallhaven.cc (alpha.wallhaven.cc)... 104.28.20.70, 104.28.21.70, 2400:cb00:2048:1::681c:1446, ...
> Connecting to alpha.wallhaven.cc (alpha.wallhaven.cc)|104.28.20.70|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: unspecified [text/html]
> Saving to: '233768’
> 
>     [ <=>                                                  ] 22,902      --.-K/s   in 0.1s
> 
> 2016-08-28 22:29:29 (185 KB/s) - '233768’ saved [22902]
> 
> --2016-08-28 22:29:29--  https://alpha.wallhaven.cc/wallpaper/401665
> Resolving alpha.wallhaven.cc (alpha.wallhaven.cc)... 104.28.21.70, 104.28.20.70, 2400:cb00:2048:1::681c:1546, ...
> Connecting to alpha.wallhaven.cc (alpha.wallhaven.cc)|104.28.21.70|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: unspecified [text/html]
> Saving to: '401665’
> 
>     [ <=>                                                  ] 22,486      --.-K/s   in 0.1s
> 
> 2016-08-28 22:29:31 (188 KB/s) - '401665’ saved [22486]
> 
> --2016-08-28 22:29:32--  https://alpha.wallhaven.cc/wallpaper/153802
> Resolving alpha.wallhaven.cc (alpha.wallhaven.cc)... 104.28.20.70, 104.28.21.70, 2400:cb00:2048:1::681c:1446, ...
> Connecting to alpha.wallhaven.cc (alpha.wallhaven.cc)|104.28.20.70|:443... connected.
> HTTP request sent, awaiting response... ^C

**Comment by macearl** [comment]
I dont have much time right now, but with the changes i just submitted it should work again, now i just need to find some time for some refactoring so that the code is actually readable again...

**Comment by Alteration** [comment]
Thanks for working on it so quickly, tested it out and works perfectly haven't noticed any issues so far
