### ISSUE TITLE
Some Location Automation.

### ISSUE THREAD

**Issue by Timelord83** [macearl/Wallhaven-Downloader#15]
Not sure you'd want to do this for the whole script but I'd love to be able to execute the script with the  -q "Mustang" and have it use all the defaults I've entered from the script but instead of the location being hard set to 

/home/timelord83/desktop/WallRips/ 

and every search term downloading to that one folder.. I'd like to automatically add the term to the end of the location. So the wallpapers would be stored in 

/home/timelord83/Desktop/WallRips/Mustang/ 

but the only var I entered into the execute command was ./wallhaven.sh -q "Mustang". I looked into the file and I if you'd be willing I'd love a hand with the modifications for my personal use if you deem the change to arbitrary for mainstream use. I realize the script can be executed with the -l and the whole path re-typed but I trying to avoid fat fingering the location by reducing the chance of user error by having the script automatically add the searched term to the end of the path since it already checks for the folder before starting it would then create it.

**Comment by doctorfree** [comment]
I use a Bash script front-end to wallhaven to do something similar to what you describe. See attachment.

[get-search.txt](https://github.com/macearl/Wallhaven-Downloader/files/487757/get-search.txt)

**Comment by macearl** [comment]
If it is just the subfolder for a search query this should do it:
```
--- /Wallhaven-Downloader/wallhaven_test.sh 
+++ /Wallhaven-Downloader/wallhaven.sh 
@@ -321,11 +321,6 @@
     shift # past argument or value
     done
 
-if [ "$TYPE" == search ]
-then
-    LOCATION+=/$(echo "$QUERY" | sed -e "s/ /_/g" -e "s/+/_/g" -e  "s/\///g")
-fi
-
 # creates Location folder if it does not exist
 if [ ! -d "$LOCATION" ]
 then
```

I only added the removal of / from the directory name to the sed command from doctorfree, also removing the whitespaces and + is optional as those are valid characters for a directory name (at least on the linux side, not sure how it works if run from cygwin im guessing you would need to replace a couple of additional special characters as well).

Im also not sure if wallhaven actually supports search operators yet so including a + in your query might actually do nothing.

This would also redownload some wallpapers as each search query would have its own downloaded file

**Comment by Timelord83** [comment]
I am using Ubuntu 16.04.01 LTS @macearl I am looking just add the search term to the location value.. Its late so maybe I am not understanding your method but it seems like its modifying the search term as well?

 @doctorfree yes that is exactly what i was looking for in the main script.. that it treats the main download folder as a global.. then adds the search query to the end and if id doesn't exist.. creates it.

**Comment by Timelord83** [comment]
I managed to get it.. I robbed a section of @doctorfree script to add it to the main script. works perfect. borrowed the changing of +'s and spaces to _'s and I am running a test download it appears to be working perfect.. thank you Gents

**Comment by macearl** [comment]
Thats pretty much what my snippet does, it just checks if you are in search mode and if you are it adds the Search query to the Global Directory, additionally it replaces spaces and + with _ and removes any / from the search query

also just pushed the changes
