### ISSUE TITLE
Different amount of wallpaper?

### ISSUE THREAD

**Issue by Osakawa** [macearl/Wallhaven-Downloader#16]
Hello, when i download with "search" option, it downloads different amount of wallpaper everytime. I mean, I check on wallhaven.cc and search "amanda cerny" and it says there are 276 wallpaper about it but when i download it downloads 188 of it and i start downloand again, this time it downloads 176 of it, everytime different. So, i had to run the script about 10 times for downloanding all wallpapers(276).  All settings(options) in script same as wallhaven.cc(i mean purity option, resulition option, general-anime-people option). What is the problem?

**Comment by Osakawa** [comment]
Also i can see in the terminal it doesnt download all of the wallpapers in a page, i mean there is 24 thumbs on a page and it doesnt download all of it, it passes to other page without downloading. You can see in the picture it downloaded 3 wallpapers of page 2. page 1 just says -done, nothing more. 

http://oi66.tinypic.com/2db3382.jpg

**Comment by macearl** [comment]
First regarding the Screenshot:
 The `Wallpaper XXXXX already downloaded!` messages mean that this is a wallpaper which was already downloaded in the past (delete the downloaded.txt file to reset this)

Now to the search:
At the time of writing this the wallhaven website returns 277 Wallpaper with your search term (all resolutions, aspect ratios, categories and purity filter) and the script downloads 277 Wallpapers with the following settings (everything else was left at the default value):
```
USER="myusername"
PASS="mypassword"

WPNUMBER=480
TYPE=search
CATEGORIES=111
FILTER=111
RESOLUTION=
ASPECTRATIO=
MODE=relevance
ORDER=desc
QUERY="amanda cerny"
THUMBS=24
```
with my account set to display 24 Thumbnails per Image, the THUMBS setting in the script must match the setting on the website

So it seems to be working on my end, try deleting the downloaded.txt file or changing your settings

**Comment by Osakawa** [comment]
first of all, really thank you for your fast answer. I did what you say and
i noticed it my "mode" was "random" when i turned to relevance it
downloaded 277 of them, maybe it was because of mode or my internet
connection speed. So really thank you for yor help and your script. By the
way, what is this script's language? and do you know where can i found any
learning material of it?

2017-01-10 0:06 GMT+03:00 macearl <notifications@github.com>:

**Comment by macearl** [comment]
No problem, its a bash script, pretty common for not too complex scripting stuff in linux/unix systems.

Cant point you to any reading material i would recommend, what i know i just picked up over the years of using linux systems (sidenote: im not really good at scripting in bash so im probably also the wrong person to ask ;) )

**Comment by Osakawa** [comment]
thank you dude, just language name enough for me :)

2017-01-10 0:52 GMT+03:00 macearl <notifications@github.com>:
