### ISSUE TITLE
syntax error: operand expected while downloading favorites

### ISSUE THREAD

**Issue by Soullivaneuh** [macearl/Wallhaven-Downloader#17]
```
$ ./wallhaven.sh -l wallhaven -t favorites
./wallhaven.sh: line 401: ((: 
            count< 48 && count< : syntax error: operand expected (error token is "< ")
```

**Comment by 2regenth** [comment]
The favorite download function is kind of a work in progress.

For now it can only download the Collection named "Default" and nothing else. (see the note in the code)

It is working for me, so if you have a Default collection and are still not able to download them provide me with more data.

**Comment by macearl** [comment]
The favorite download function is kind of a work in progress. 

For now it can only download the Collection named "Default" and nothing else. (see the note in the code) 

It is working for me, so if you have a Default collection and are still not able to download them provide me with more data.

**Comment by Soullivaneuh** [comment]
Thank for the quick reply @macearl!

Here is my favorites page:

![image](https://user-images.githubusercontent.com/1698357/27559845-4ef41f60-5ac2-11e7-9f04-0a70593e375c.png)

The collection is correctly named default. But it's a private collection, maybe this is why it's failing?

**Comment by Soullivaneuh** [comment]
I made it public but this change nothing, I got the same error.

What additional data could I provide?

**Comment by Soullivaneuh** [comment]
Okay I found why: My password contains some special chars and your script seems to not like it.

I simplify it to make it working.

Some escaping is needed I guess.

**Comment by macearl** [comment]
Glad you found the cause of this, i'll take a look at the login again and try to escape the special characters.
