### ISSUE TITLE
Make filtering option working with favorites

### ISSUE THREAD

**Issue by Soullivaneuh** [macearl/Wallhaven-Downloader#18]
It would be great to have some options like `--ratio` working with favorites download.

We can have different working PC with different resolution screens.

**Comment by macearl** [comment]
Currently not possible without a huge amount of overhead.

Wallhaven does not provide any filtering options to the favorites page (ratio, resolution, ...) the only working argument is page. It would be possible to get purity working, but also with overhead

Currently im using:
https://alpha.wallhaven.cc/favorites?page=X
To download the images in the default collection, this url does not provide any other options, one could use:
https://alpha.wallhaven.cc/user/USERNAME/favorites/COLLECTION_ID?page=x&purity=110
but for this you would first need to parse the collection id. And purity is the only additional filter there.

Using the second url is probably better in the long run, as that would at least enable purity filtering and downloading other collections than "Default"

For all other options you would need to download the page of each wallpaper in your collection and then check the ratio, resolution, ... there and depending on the outcome finally download the image

**Comment by Soullivaneuh** [comment]
@macearl Indeed, so bad. :-/

Out of subject, do you know any linux command line tool to filter image files by ratio after downloading?

Regards.

**Comment by macearl** [comment]
I would probably use one of the imagemagick tools:
Try this:
```bash
# set this to your desired aspect ratio
ref=4/3 
# the identify part lists all images with your desired ratio as "0 filename.extension" and everything else with 0.XXXX
# you can specify a filetype by changing * to *.jpg or *.png
# grep filters only the exact matching images
# sed removes the "0 " so you are left only with the list of filenames
list=$(identify -format "%[fx:abs(w/h - $ref)] %M\n" * | grep "0 " | sed  's .\{2\}  ')
# do something with your list
for img in $list
do
  cp $img /desired/path/"
done
```
based on: https://unix.stackexchange.com/questions/50252/sort-images-by-aspect-ratio/50259#50259

**Comment by Soullivaneuh** [comment]
Thanks for the tip! Here is my final script:

```bash
screen_ratio=$(xrandr | grep 'connected primary' | egrep --only-matching '[0-9]+x[0-9]+' | sed 's#x#/#')
rm --force $(identify -format "%[fx:abs(w/h - ${screen_ratio})] %M\n" ~/.wallhaven/*.jpg ~/.wallhaven/*.png | grep --invert-match "0 " | cut --delimiter ' ' --fields 2-)
```

Next step: Remove wallpapers with resolution lower than my screen. :wink:

**Comment by macearl** [comment]
```bash
ratio=$(xrandr --current | grep '*' | egrep --only-matching '[0-9]+x[0-9]+' | sed 's#x#/#')
xres=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
list=$(identify -format "%[fx:abs(w/h - $ratio)] %wx%h %M\n" * | grep "^0 " | awk ' $2 >=$xres' | cut --delimiter ' ' --fields 3-)
```

This should filter out all images smaller than your current screen resolution, also note that the previous grep 0 could lead to false positives as i did not specify it has to be at the beginning of a line.

note filenames with spaces will probably lead to errors during your rm, but if you did not rename the files they shouldn't contain any

**Comment by Soullivaneuh** [comment]
Thanks again for the tips, I'll take a look! :wink:
