### ISSUE TITLE
If I try to download my owns images, it downloads from others...

### ISSUE THREAD

**Issue by Dokop2It** [macearl/Wallhaven-Downloader#19]
See titles..
Is there a bug? If not, could you help me ?
I tried last night but wasn't successful.

**Comment by macearl** [comment]
Do you mean wallpaper you uploaded to wallhaven or your favorites? 

Could you post your config (excluding your username and password of course) 

I haven't taken a look yet, but i should be able to find some time in the next few days

**Comment by macearl** [comment]
I just tried downloading Wallpapers which i uploaded to wallhaven and everything works fine for me, i am guessing there is some mistake in your config
Make sure that you have set
```
TYPE=useruploads
USR=<yourUsername>
```
