### ISSUE TITLE
errors on LibreELEC

### ISSUE THREAD

**Issue by Diodor7** [macearl/Wallhaven-Downloader#24]
I have distro LibreELEC 8.2.5 and last version of Wallhaven-Downloader (0.1.9).
After running of script are appear errors:
```
./wallhaven.sh: line 385: LOCATION+=/nature: not found
./wallhaven.sh: line 411: syntax error: bad for loop variable
```

<details>
  <summary>part of this loop</summary>

> if [ "$TYPE" == standard ]
> then
>     **for ((  count=0, page="$STARTPAGE";**
>             count< "$WPNUMBER";
>             count=count+"$THUMBS", page=page+1 ));
>     do
>         printf "Download Page %s\\n" "$page"
>         s1="search?page=$page&categories=$CATEGORIES&purity=$FILTER&"
>         s1+="atleast=$ATLEAST&resolutions=$RESOLUTION&ratios=$ASPECTRATIO"
>         s1+="&sorting=$MODE&order=$ORDER&topRange=$TOPRANGE&colors=$COLOR"
>         getPage "$s1"
>         printf "\\t- done!\\n"
>         printf "Download Wallpapers from Page %s\\n" "$page"
>         downloadWallpapers
>         printf "\\t- done!\\n"
>     done

</details>

The first error is fixed by changing the parameter SUBFOLDER on 0. Second error it's way out of my league. Help!

**Comment by macearl** [comment]
could you post your config options as well?
The subfolder option should only matter if the mode is set to search and your other error points to the standard mode.

Also im not sure if libreelec actually ships with bash, i don't have a device handy to test libreelec on right now, i'll try to find the R-Pi i should have lying around somewhere and give it a go on there. If you could check beforehand if bash is actually installed and if which version it would probably help alot.

**Comment by macearl** [comment]
if you are running libreelec on a R-Pi you could try [OSMC](https://osmc.tv/) instead, iirc [OSMC](https://osmc.tv/) is based on debian and includes more packages (and allows to install additional packages through apt-get)

changing the script to work on a pure bourne shell is not something i was planning to do

**Comment by Diodor7** [comment]
In that case, I will use the script on another system.
Thank you for your support!
