### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by Maveee** [macearl/Wallhaven-Downloader#27]
Suddenly get this error (worked fine yesterday)

https://i.imgur.com/ZWGTEa7.png

`assertion "cb == jq_util_input_next_input_cb" failed: file "/usr/src/ports/jq/jq-1.6-1.x86_64/src/jq-1.6/src/util.c", line 371, function: jq_util_input_get_position`

**Comment by macearl** [comment]
It's working for me, could you post some additional information regarding your setup?

I assume you're running the script under windows through cygwin?

**Comment by Maveee** [comment]
> 
> 
> It's working for me, could you post some additional information regarding your setup?
> 
> I assume you're running the script under windows through cygwin?

That is correct, I've been running it through cygwin for over a year. Setup is basically cygwin and everything required for cygwin to run wallhaven-downloader. (I only use cygwin for your script)

Sadly I'm still getting the errors, also getting a parse error in another .sh file now.

![image](https://user-images.githubusercontent.com/8791604/59332312-388b2f80-8cf6-11e9-84f4-e628264e18ed.png)

**Comment by macearl** [comment]
could you show me the scripts your using? Or did you only change the resolution in each?

Im not sure about the assertion error, but the parse error could be related to the continue option for wget.
Try deleting the tmp file in your folder if it exists, alternatively try another clean directory for now. I also removed the continue option with the latest update, you could also try that.

**Comment by Maveee** [comment]
This is what I get from a clean file:

![image](https://user-images.githubusercontent.com/8791604/59382496-2b099000-8d5e-11e9-991a-06d83b69926c.png)

Nothing is changed in here, not even api key or resolution, all clean from your latest commit.

**Comment by macearl** [comment]
Ok so i just set up a Windows VM with cygwin and everything seems to work fine.

```
VM@DESKTOP ~
$ curl -o wallhaven.sh "https://raw.githubusercontent.com/macearl/Wallhaven-Downloader/master/wallhaven.sh"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16947  100 16947    0     0  16947      0  0:00:01 --:--:--  0:00:01 33894

VM@DESKTOP ~
$ chmod +x wallhaven.sh

VM@DESKTOP ~
$ sed -i 's/\/location\/to\/your\/wallpaper\/folder/\/home\/VM\/wallpaper\//g' wallhaven.sh

VM@DESKTOP ~
$ ./wallhaven.sh
Checking dependencies...OK
Download Page 1
        - done!
Download Wallpapers from Page 1
        - done!
Download Page 2
        - done!
Download Wallpapers from Page 2
        - done!

VM@DESKTOP ~
$ bash --version
GNU bash, version 4.4.12(3)-release (x86_64-unknown-cygwin)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

VM@DESKTOP ~
$ wget --version
GNU Wget 1.19.1 built on cygwin.

-cares +digest -gpgme +https +ipv6 +iri +large-file -metalink +nls
+ntlm +opie +psl +ssl/gnutls

Wgetrc:
    /etc/wgetrc (system)
Locale:
    /usr/share/locale
Compile:
    gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/etc/wgetrc"
    -DLOCALEDIR="/usr/share/locale" -I.
    -I/usr/src/wget-1.19.1-2.x86_64/src/wget-1.19.1/src -I../lib
    -I/usr/src/wget-1.19.1-2.x86_64/src/wget-1.19.1/lib
    -I/usr/include/uuid -DNDEBUG -ggdb -O2 -pipe
    -Wimplicit-function-declaration
    -fdebug-prefix-map=/usr/src/wget-1.19.1-2.x86_64/build=/usr/src/debug/wget-1.19.1-2
    -fdebug-prefix-map=/usr/src/wget-1.19.1-2.x86_64/src/wget-1.19.1=/usr/src/debug/wget-1.19.1-2
Link:
    gcc -I/usr/include/uuid -DNDEBUG -ggdb -O2 -pipe
    -Wimplicit-function-declaration
    -fdebug-prefix-map=/usr/src/wget-1.19.1-2.x86_64/build=/usr/src/debug/wget-1.19.1-2
    -fdebug-prefix-map=/usr/src/wget-1.19.1-2.x86_64/src/wget-1.19.1=/usr/src/debug/wget-1.19.1-2
    -lpcre -luuid -lidn2 -lnettle -lgnutls -lz -lpsl ftp-opie.o
    gnutls.o http-ntlm.o ../lib/libgnu.a -liconv -lintl

Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
<http://www.gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Originally written by Hrvoje Niksic <hniksic@xemacs.org>.
Please send bug reports and questions to <bug-wget@gnu.org>.

VM@DESKTOP ~
$ jq --version
jq-1.6

VM@DESKTOP ~
$ sed --version
sed (GNU sed) 4.4
Packaged by Cygwin (4.4-1)
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jay Fenlason, Tom Lord, Ken Pizzini,
and Paolo Bonzini.
GNU sed home page: <http://www.gnu.org/software/sed/>.
General help using GNU software: <http://www.gnu.org/gethelp/>.
E-mail bug reports to: <bug-sed@gnu.org>.

VM@DESKTOP ~
$
```

Seeing as it works on a fresh install i have to assume that some cygwin setup change or update on your machine is responsible.  I included the installed versions of the dependencies in my output so you can check them against yours.

Did you try to run the script in a clean directory (a directory without any files created through the script, e.g. downloaded.txt tmp download.txt wallhaven-XXXXXX.jpg ) yet?

**Comment by Maveee** [comment]
Thank you, I have reinstalled all the packages, redownloaded the latest wallhaven-downloader version and it's working now. Not sure what exactly caused it though.., but hey it works again!
