### ISSUE TITLE
Download Only Anime Category

### ISSUE THREAD

**Issue by KingpinTR** [macearl/Wallhaven-Downloader#28]
TYPE=search,
QUERY="id:37"
MODE=date_added,
STARTPAGE=1,
CATEGORIES=111,
FILTER=111,
PARALLEL=1,

**TMP File :**

{"id":"nmd9d1","url":"https:\/\/wallhaven.cc\/w\/nmd9d1","short_url":"https:\/\/whvn.cc\/nmd9d1","views":2806,"favorites":4,"source":"","purity":"sfw","category":"anime","dimension_x":1920,"dimension_y":1200,"resolution":"1920x1200","ratio":"1.6","file_size":213081,"file_type":"image\/jpeg","created_at":"2014-09-21 07:54:58","colors":["#ffffff","#999999","#424153","#e7d8b1","#cccccc"],"path":"https:\/\/w.wallhaven.cc\/full\/nm\/wallhaven-nmd9d1.jpg","thumbs":{"large":"https:\/\/th.wallhaven.cc\/lg\/nm\/nmd9d1.jpg","original":"https:\/\/th.wallhaven.cc\/orig\/nm\/nmd9d1.jpg","small":"https:\/\/th.wallhaven.cc\/small\/nm\/nmd9d1.jpg"}},

{"id":"n6kokl","url":"https:\/\/wallhaven.cc\/w\/n6kokl","short_url":"https:\/\/whvn.cc\/n6kokl","views":2189,"favorites":3,"source":"","purity":"sfw","category":"anime","dimension_x":1680,"dimension_y":1050,"resolution":"1680x1050","ratio":"1.6","file_size":112175,"file_type":"image\/jpeg","created_at":"2014-09-21 07:54:58","colors":["#424153","#000000","#999999","#cccccc","#996633"],"path":"https:\/\/w.wallhaven.cc\/full\/n6\/wallhaven-n6kokl.jpg","thumbs":{"large":"https:\/\/th.wallhaven.cc\/lg\/n6\/n6kokl.jpg","original":"https:\/\/th.wallhaven.cc\/orig\/n6\/n6kokl.jpg","small":"https:\/\/th.wallhaven.cc\/small\/n6\/n6kokl.jpg"}},

{"id":"473239","url":"https:\/\/wallhaven.cc\/w\/473239","short_url":"https:\/\/whvn.cc\/473239","views":2490,"favorites":3,"source":"","purity":"sfw","category":"anime","dimension_x":1920,"dimension_y":1200,"resolution":"1920x1200","ratio":"1.6","file_size":458846,"file_type":"image\/png","created_at":"2014-09-21 07:54:58","colors":["#424153","#000000","#cc0000","#993399","#996633"],"path":"https:\/\/w.wallhaven.cc\/full\/47\/wallhaven-473239.png","thumbs":{"large":"https:\/\/th.wallhaven.cc\/lg\/47\/473239.jpg","original":"https:\/\/th.wallhaven.cc\/orig\/47\/473239.jpg","small":"https:\/\/th.wallhaven.cc\/small\/47\/473239.jpg"}}],"meta":{"current_page":1,"last_page":5,"per_page":"64","total":298,"query":""}}

**Comment by macearl** [comment]
should be fixed now, the problem was that the option for useruploads was always appended to the search
