### ISSUE TITLE
Wallpapers stop downloading after certain point

### ISSUE THREAD

**Issue by Maveee** [macearl/Wallhaven-Downloader#29]
I'm downloading all wallpapers in the 16x9 ratio with a resolution higher than 1921x1080
This works perfect for the first 1246 pages, however, from page 1247 onwards, the wallpapers stop downloading (they don't appear in the folder), yet the terminal window still continues:

![afbeelding](https://user-images.githubusercontent.com/8791604/60020677-c836c380-9690-11e9-9acf-e01651599681.png)

as if nothing is wrong... (it goes really fast as well)

Any idea what might cause this?

The downloaded.txt file is also "stuck" on this:

![afbeelding](https://user-images.githubusercontent.com/8791604/60020790-02a06080-9691-11e9-8df4-1b73a3df0142.png)

meaning, no matter how much longer I let the .sh file run past page 1246, no extra wallpapers get added.

Thank you in advance! (and sorry to discover another issue for me)

**Comment by Maveee** [comment]
Well, I'm an idiot. There are no more wallpapers to download: https://wallhaven.cc/search?categories=111&purity=100&atleast=1921x1080&ratios=16x9&sorting=date_added&order=desc 
29890 is the total amount available, I'm hitting that limit..
Maybe it could be interesting to show a warning message though? "No more wallpapers to download!" or something.

**Comment by macearl** [comment]
I never tried to download all the wallpapers matching the options before, so it did not occur to me to check if the last page was reached.

I just pushed a new update which adds a last page check and stops the script after it has been downloaded
