### ISSUE TITLE
API

### ISSUE THREAD

**Issue by yeappa** [macearl/Wallhaven-Downloader#30]
not issue!
how to appy an api to retrive code
this sample gives this respond: **Please make sure to enter a valid API key,**

> bash wallhaven.sh -f 111 -m date_added -q "Guenter Stoehr"

**Comment by macearl** [comment]
You will need an account for wallhaven for this.
Sign into the wallhaven website and go to: https://wallhaven.cc/settings/account
copy the api key you see there and enter it between the quotation marks in line 16 of the script: https://github.com/macearl/Wallhaven-Downloader/blob/e83b38ee7c26f2f03653d28f358bd898e2a876a9/wallhaven.sh#L11-L19
