### ISSUE TITLE
Only show downloaded wallpapers.

### ISSUE THREAD

**Issue by oppsig** [macearl/Wallhaven-Downloader#4]
I wonder if you could implement an enhancement.
Right now the program only lists wallpapers already downloaded,
which is not that interesting information.
Maybe it would be better to list only new wallpapers downloaded.

Like 
Downloaded: wallhaven-00001.jpg, wallhaven-00002.jpg, wallhaven-00013.jpg.

Or

Grabbed 3 new wallpapers.

**Comment by oppsig** [comment]
Ok I didnt notice you could have sorting set to randompt in the scri. I had it on favorites which produces quite a lot of spam, and only sometimes getting new wallpapers :)
I wanted to grab the most popular ones. So I guess this is not much of an issue really.

**Comment by macearl** [comment]
The downloaded.txt file is mainly to keep track of already downloaded wallpapers to reduce the number of duplicates.

But if your still interested in some sort of statistic feature let me know, although it might take some time for me to implement it, given the fact that it is not a crucial feature and time is not an endless resource ;)
